configVersion: "1.0"

# Profile
name: "Harshit Mani Tripathi"
subtitle: "DevOps | SRE "
description: |
  Hybrid infrastructure platform
  Serving ~500k DNS queries
  Automated via Terraform
  
  Public uptime@
  status.hudater.dev
avatar: "https://res.cloudinary.com/djsasyvfl/image/upload/v1764407361/cropped_circle_image_pz7ua1.png"
favicon: "https://res.cloudinary.com/djsasyvfl/image/upload/v1764407384/favicon_josj9j.ico"

## Analytics
analytics:
    google:
        id: "G-MSTPBLQLXE"
    goatcounter:
        id: "hudater-linkme"
        selfhosted: false
    plausible:
        domain: "" # tracked site
        script_url: ""

# Theme selection
theme: "default"

# Background options
# type: color | image | gradient | particles
background:
    type: "color"
    value: "#1e1f26"

# Main links (large buttons)
# icon: Simple Icons slug (see https://simpleicons.org)
# color: hex color for button background
links:
    - title: "Infra Uptime Dashboard"
      url: "https://status.hudater.dev"
      icon: "server"
      icon-provider: "lucide"
      color: "#166534"

    - title: "Portfolio"
      url: "https://hudater.dev"
      icon: "briefcase-business"
      icon-provider: "lucide"
      color: "#111111"

    - title: "GitHub: Hudater"
      url: "https://github.com/Hudater"
      icon: "github"
      color: "#0a0a0a"

    - title: "Personal Tech Blog"
      url: "https://blog.hudater.dev"
      icon: "rss"
      icon-provider: "simpleicon"
      color: "#BF2424"

    # - title: "Technical Docs"
    #   url: "https://docs.hudater.dev"
    #   icon: "notebook-text"
    #   icon-provider: "lucide"
    #   color: "#222222"

    - title: "DevOps / SRE Resume"
      url: "https://resume.hudater.dev"
      icon: "file-user"
      icon-provider: "lucide"
      color: "#2563EB"

# Sections with headings
sections:
    - title: "Projects"
      links:
          - title: "Automated Infrastructure"
            url: "https://github.com/hudater/infra_lab/"
            icon: "opentofu"
            color: "#4f239b"

          - title: "My Homelab!"
            url: "https://blog.hudater.dev/posts/homelab/"
            iconUrl: "assets/icons/selfhosted.png"
            color: "#ee7125"

          - title: "Cohort Assignments and Blogs"
            url: "https://cohort.hudater.dev/"
            icon: "rss"
            color: "#9A3412"

# Social links (small icons)
socials:
    - icon: "gmail"
      icon-provider: "simpleicon"
      url: "mailto:harshit@hudater.dev"
      color: "#EA4335"
    - icon: "linkedin"
      icon-provider: "simpleicon"
      url: "https://www.linkedin.com/in/hudater"
      color: "#005FF9"
    - icon: "x"
      icon-provider: "simpleicon"
      url: "https://twitter.com/hudater_"
      color: "#FFFFFF"
    - icon: "reddit"
      icon-provider: "simpleicon"
      url: "https://www.reddit.com/user/hudater"
      color: "#FF4500"
